production:
	adapter: mysql2
	database: skmz_ozerki24
	user: skmz_ozerki24
	password: VYWWvdTn
	encoding: utf8

development:
	adapter: sqlite3
	database: db/skmz.hostel.dev.sqlite3
	pool: 5
	timeout: 5000