development:
  adapter: sqlite3
  database: db/skmz.hostel.dev.sqlite3
  pool: 5
  timeout: 5000
# production:
#   adapter: mysql2
#   encoding: utf8
#   host: mysql5.locum.ru
#   database: skmz_hostel41
#   username: skmz_hostel41
#   password: QQmc2E9A
production:
  adapter: sqlite3
  database: db/skmz.hostel.dev.sqlite3
  pool: 5
  timeout: 5000