development:
  adapter: sqlite3
  database: db/skmz.hostel.dev.sqlite3
  pool: 5
  timeout: 5000
production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: skmz_ozerki24
  username: skmz_ozerki24
  password: VYWWvdTn
