CategoryNew.create(title: 'News')
CategoryNew.create(title: 'Stocks')
Page.create(title: 'Services', text: 'Services', snippet: 'Services', keywords: 'Services')
Page.create(title: 'Contacts', text: 'Contacts', snippet: 'Contacts', keywords: 'Contacts')
Page.create(title: 'History', text: 'History', snippet: 'History', keywords: 'History')
Page.create(title: 'Prices', text: 'Prices', snippet: 'Prices', keywords: 'Prices')
Page.create(title: 'Leisure', text: 'Leisure', snippet: 'Leisure', keywords: 'Leisure')